#lang racket

; Creates a new type
(define-syntax make-type
  (syntax-rules ()
    ((_ type params ...)
     (define (type params ...)
        (list ( list 'params params) ... )
       )
     )
    )
  )

; Components definition
(make-type component id properties)

; Systems definition
(make-type system id required-components)

; Instantiations
(define (comp-phys) (component 'Physics '(x y z)))
(system 'collision-detection '('Physics))




(define (component-to-rust c)
  (define (identifier) (cdr (car(c))))
  (define (properties) (cdr(c)))
  (~a
            (append
             '("pub struct ") (identifier) '(" {")
             (properties)

             '("}"
             )
             )
            )
           
  )

(display "This is an autogenerated file")
(display "\n")
(display (component-to-rust comp-phys))