[package]
name = "valkyrie_core"
version = "0.1.0"
authors = ["Eric Olson <eric.rob.olson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threading = {path="crates/threading"}
file_io = {path="crates/file_io"}
renderer = {path="crates/renderer"}
window = {path="crates/window"}
data_structures = {path = "crates/data_structures"}
ecs = {path = "crates/ecs"}
timing = {path = "crates/timing"}

# Platform specific dependencies
platform_file_io = {path="crates/_platform_specific/platform_file_io"}
platform_threading = {path="crates/_platform_specific/platform_threading"}
platform_window_gfx = {path="crates/_platform_specific/platform_window_gfx"}
